services:
  - type: web
    name: lotto-prophet-api
    runtime: node
    repo: "./"
    rootDir: server
    buildCommand: "cd server && yarn install --frozen-lockfile && yarn build"
    startCommand: "cd server && yarn start"
    env:
      - key: NODE_ENV
        value: production

