services:
  - type: web
    name: lotto-prophet-api
    runtime: node
    repo: "./"
    rootDir: server
    buildCommand: "cd server && npm ci && npm run build"
    startCommand: "cd server && npm run start"
    env:
      - key: NODE_ENV
        value: production

