services:
  - type: web
    name: lotto-prophet-api
    runtime: node
    repo: "./"
    rootDir: server
    buildCommand: "npm ci --prefix server"
    startCommand: "npm run start"
    env:
      - key: NODE_ENV
        value: production
